<?php

use Illuminate\Database\Seeder;
use App\Seed;
use App\Illness;

class SeedTableSeeder extends Seeder
{
    /**
     * Run the database seed.
     *
     * @return void
     */
    public function run()
    {
        DB::table('seeds')->delete();
        DB::table('illnesses')->delete();
        DB::table('seeds_illnesses')->delete();
        DB::table('seeds_permacultures')->delete();

        /* Seeds */

        $tomatoes = Seed::create([
            'name' => 'tomate',
            'latin_name' => 'Solanum lycopersicum',
            'variety' => 'coeur de boeuf',
            'type' => 'solanacée',
            'exposure' => 'ensoleillé',
            'water' => '1 l/jour',
            'fertilizer' => '',
            'planting_period_start' => '2018-03-01',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2018-10-31',
            'harvest_within_time' => 90,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '1.79',
            'difficulty' => 'hard',
            'tutorial' => 'lorem',
            'advices' => 'lorem'
        ]);

        $potatoes = Seed::create([
            'name' => 'pomme de terre',
            'latin_name' => 'Solanum tuberosum',
            'variety' => 'bintje',
            'type' => 'tubercule',
            'exposure' => 'ensoleillé',
            'water' => '1 l/jour',
            'fertilizer' => '',
            'planting_period_start' => '2018-03-01',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2018-10-31',
            'harvest_within_time' => 120,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '1.79',
            'difficulty' => 'hard',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'limons fins',
        ]);

        $eggplant = Seed::create([
            'name' => 'aubergine',
            'latin_name' => 'Solanum melongena',
            'variety' => 'Barbentane longue',
            'type' => 'solanacée',
            'exposure' => 'ensoleillé',
            'water' => 'modéré',
            'fertilizer' => 'Phacélie ou épinards',
            'planting_period_start' => '2018-02-28',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-06-01',
            'harvest_period_end' => '2018-09-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'hard',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'limons fins',
        ]);
        $chili = Seed::create([
            'name' => 'piment',
            'latin_name' => 'Capsicum annuum',
            'variety' => 'Piment d\'Espelette',
            'type' => 'solanacée',
            'exposure' => 'ensoleillé',
            'water' => 'modéré',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-03-01',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-08-01',
            'harvest_period_end' => '2018-10-31',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '1.79',
            'difficulty' => 'medium',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'limons fins',
        ]);
        $cabage = Seed::create([
            'name' => 'chou',
            'latin_name' => 'Solanum tuberosum',
            'variety' => 'bintje',
            'type' => 'tubercule',
            'exposure' => 'ensoleillé',
            'water' => '1 l/jour',
            'fertilizer' => '',
            'planting_period_start' => '2018-03-01',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2018-10-31',
            'harvest_within_time' => 80,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '1.79',
            'difficulty' => 'hard',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'limons fins',
        ]);
        $leek = Seed::create([
            'name' => 'poireau',
            'latin_name' => 'Allium porrum',
            'variety' => 'Poireau de Liège',
            'type' => 'liliacée',
            'exposure' => 'ensoleillé',
            'water' => 'faible',
            'fertilizer' => 'Ne nécessite aucun engrais',
            'planting_period_start' => '2018-01-15',
            'planting_period_end' => '2018-09-15',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2019-02-28',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'sables fins',
        ]);

         $salade = Seed::create([
            'name' => 'salade',
            'latin_name' => 'Lactuca sativa',
            'variety' => 'Laitue pommée',
            'type' => 'asteracée',
            'exposure' => 'ensoleillé / mi-ombre',
            'water' => 'abondant',
            'fertilizer' => 'Ne nécessite aucun engrais',
            'planting_period_start' => '2018-01-01',
            'planting_period_end' => '2018-10-30',
            'harvest_period_start' => '2018-01-01',
            'harvest_period_end' => '2019-12-31',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $haricot = Seed::create([
            'name' => 'haricot',
            'latin_name' => 'Phaseolus vulgaris',
            'variety' => 'Roi des Belges',
            'type' => 'fabacée',
            'exposure' => 'ensoleillé',
            'water' => 'modéré',
            'fertilizer' => 'Seigle ou phacélie',
            'planting_period_start' => '2018-05-01',
            'planting_period_end' => '2018-07-31',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2019-09-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '4.50',
            'difficulty' => 'medium',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'sables fins',
        ]);

        $fraises = Seed::create([
            'name' => 'fraise',
            'latin_name' => 'Fragaria vesca',
            'variety' => 'Gorella',
            'type' => 'rosacée',
            'exposure' => 'ensoleillé / mi-ombre',
            'water' => 'abondant',
            'fertilizer' => 'Ne nécessite aucun engrais',
            'planting_period_start' => '2018-09-01',
            'planting_period_end' => '2018-09-30',
            'harvest_period_start' => '2018-05-01',
            'harvest_period_end' => '2019-10-31 ',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '4.00',
            'difficulty' => 'medium',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'sables fins',
        ]);

        $courgette = Seed::create([
            'name' => 'courgette',
            'latin_name' => 'Cucurbita pepo',
            'variety' => 'Nimba',
            'type' => 'cucurbitacée',
            'exposure' => 'ensoleillé',
            'water' => 'modéré',
            'fertilizer' => 'Compost ou fumier.',
            'planting_period_start' => '2018-05-01',
            'planting_period_end' => '2018-06-30',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2019-10-31 ',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'sables fins',
        ]);

        $celeri = Seed::create([
            'name' => 'céleri rave',
            'latin_name' => 'Apium graveolens',
            'variety' => 'Monarch',
            'type' => 'apiacée',
            'exposure' => 'ensoleillé',
            'water' => 'abondant',
            'fertilizer' => 'Compost ou fumier.',
            'planting_period_start' => '2018-04-15',
            'planting_period_end' => '2018-06-15',
            'harvest_period_start' => '2018-08-01',
            'harvest_period_end' => '2018-11-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $epinard = Seed::create([
            'name' => 'épinard',
            'latin_name' => 'Spinocia oleracea',
            'variety' => 'Géant d\'hiver',
            'type' => 'amaranthacées',
            'exposure' => 'mi-ombre',
            'water' => 'modéré',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-08-01',
            'planting_period_end' => '2018-09-30',
            'harvest_period_start' => '2018-09-15',
            'harvest_period_end' => '2018-11-15',
            'harvest_within_time' => 45,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $carotte = Seed::create([
            'name' => 'carotte',
            'latin_name' => 'Daucus carota',
            'variety' => 'De la Halle',
            'type' => 'apiacée',
            'exposure' => 'ensoleillé / mi-ombre',
            'water' => 'modéré',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-03-01',
            'planting_period_end' => '2018-07-31',
            'harvest_period_start' => '2018-04-15',
            'harvest_period_end' => '2018-09-15',
            'harvest_within_time' => 45,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'sables fins',
        ]);

        $concombre = Seed::create([
            'name' => 'concombre',
            'latin_name' => 'Cucumis sativus',
            'variety' => 'Généreux',
            'type' => 'cucurbitacée',
            'exposure' => 'ensoleillé',
            'water' => 'abondant',
            'fertilizer' => 'Fumier',
            'planting_period_start' => '2018-04-01',
            'planting_period_end' => '2018-06-30',
            'harvest_period_start' => '2018-07-15',
            'harvest_period_end' => '2018-09-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'medium',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $rhubarbe = Seed::create([
            'name' => 'rhubarbe',
            'latin_name' => 'Rheum rhaponticum',
            'variety' => 'Red Champagne',
            'type' => 'polygonacée',
            'exposure' => 'ensolleillé / mi-ombre',
            'water' => 'abondant',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-04-01',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-05-01',
            'harvest_period_end' => '2018-09-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 11,
            'soil_humus_percent'=> 80,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $framboise = Seed::create([
            'name' => 'framboise',
            'latin_name' => 'Rubus idaeus',
            'variety' => 'Lloyd George',
            'type' => 'rosacée',
            'exposure' => 'ensolleillé / mi-ombre',
            'water' => 'faible',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-11-01',
            'planting_period_end' => '2018-03-31',
            'harvest_period_start' => '2018-06-15',
            'harvest_period_end' => '2018-10-15',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $cassis = Seed::create([
            'name' => 'cassis',
            'latin_name' => 'Ribes nigrum',
            'variety' => 'Andega',
            'type' => 'grossulariacées',
            'exposure' => 'mi-ombre',
            'water' => 'faible',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-09-01',
            'planting_period_end' => '2018-11-30',
            'harvest_period_start' => '2018-07-01',
            'harvest_period_end' => '2018-08-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $chourouge = Seed::create([
            'name' => 'chou rouge',
            'latin_name' => 'Brassica oleracea ',
            'variety' => 'Tête noire',
            'type' => 'brassicacée',
            'exposure' => 'ensoleillé',
            'water' => 'abondant',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-02-15',
            'planting_period_end' => '2018-03-31',
            'harvest_period_start' => '2018-09-15',
            'harvest_period_end' => '2018-11-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'calcaire',
        ]);

        $persil = Seed::create([
            'name' => 'persil',
            'latin_name' => 'Petroselinum crispum',
            'variety' => 'Persil commun',
            'type' => 'apiacée',
            'exposure' => 'ensoleillé / mi-ombre',
            'water' => 'abondant',
            'fertilizer' => 'Ne nécessite aucun engrais.',
            'planting_period_start' => '2018-05-01',
            'planting_period_end' => '2018-09-30',
            'harvest_period_start' => '2018-06-01',
            'harvest_period_end' => '2018-10-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/tomate_fruit.jpg',
            'seed_img_url' => '/tomate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'easy',
            'tutorial' => '',
            'advices' => '',
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'calcaire',
        ]);

        $chives = Seed::create([
            'name' => 'ciboulette',
            'latin_name' => 'Allium schoenoprasum',
            'variety' => 'ciboulette sauvage',
            'type' => 'herbe',
            'exposure' => 'mi-ombre',
            'water' => 'faible',
            'fertilizer' => 'aucun engrais nécessaire',
            'planting_period_start' => '2018-09-01',
            'planting_period_end' => '2018-11-30',
            'harvest_period_start' => '2018-06-01',
            'harvest_period_end' => '2018-11-30',
            'harvest_within_time' => 45,
            'grown_img_url' => '/ciboulette_fruit.jpg',
            'seed_img_url' => '/ciboulette_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => "1. Tracer des sillons de 1 à 2 cm de profondeur dans la terre. 2. Semer clair en espacant les graines de 5 à 10cm de façon à former des plants différents. 3. Recouvrir de terre fine les semences et tasser. 4. Arroser en pluie fine. 5. Maintenir la terre humide jusqu'a ce que les feuilles apparaissent.",
            'advices' => "1. Couper fréquemment pour stimuler la pousse des feuilles. 2. Couper les fleurs lorsqu'elles apparaissent pour ne pas affaiblir le plant. 3. Couper le bouquet à 5cm de la base lorsqu'il commence à ramolir. "				,
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'all',
        ]);

        $radis = Seed::create([
            'name' => 'radis',
            'latin_name' => 'Raphanus sativus',
            'variety' => 'radis rond écarlate',
            'type' => 'racine',
            'exposure' => 'ensoleillé',
            'water' => 'modéré',
            'fertilizer' => 'aucun engrais nécessaire',
            'planting_period_start' => '2018-01-01',
            'planting_period_end' => '2018-09-01',
            'harvest_period_start' => '2018-02-01',
            'harvest_period_end' => '2018-10-01',
            'harvest_within_time' => 35,
            'grown_img_url' => '/radis_rond_ecarlate_fruit.jpg',
            'seed_img_url' => '/radis_rond_ecarlate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'easy',
            'tutorial' => "1. Semer à la volée sous abri de janvier à mars. 2. Couvrir d'une fine couche de terreau, environ 1cm. 3. Tasser légèrement le sol. 4. Éclaircir lorsque les premières feuilles apparaissent.\"",
            'advices' => "1. Lorsque le semis sort de terre, retirer les petites feuilles et conservez uniquement les plants plus vigoureux tous les 4-5cm. 2. Maintenir le sol propre en désherbant régulièrement pour faciliter l'écoulement de l'arrosage. 3. Le radis se récolte régulièrement dès qu'il est formé. Mieux vaut récolter un radis trop petit que trop gros. \"			"				,
            'soil_ph'=> 7,
            'soil_humus_percent'=> 5,
            'soil_granulometry'=> 'all',
        ]);

        $potimarron = Seed::create([
            'name' => 'potimarron',
            'latin_name' => 'Cucurbita maxima',
            'variety' => 'Maxima Duch',
            'type' => 'cucurbitacée',
            'exposure' => 'ensoleillé',
            'water' => 'modéré',
            'fertilizer' => 'Compost ou fumier.',
            'planting_period_start' => '2018-04-01',
            'planting_period_end' => '2018-05-31',
            'harvest_period_start' => '2018-09-01',
            'harvest_period_end' => '2018-11-30',
            'harvest_within_time' => 0,
            'grown_img_url' => '/radis_rond_ecarlate_fruit.jpg',
            'seed_img_url' => '/radis_rond_ecarlate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'super easy',
            'tutorial' => "1. Enfoncer les graines légèrement pointes vers le bas dans un sol fertile. Penser donc à apporter du compost ou du fumier en plus. 2. Espacer les pieds des plantes de 2m. 3. Arroser 2 fois par semaine en début de culture. 4. Dès l'apparition des premiers fruits, veiller à ne pas laisser sécher la terre. Couvrer le pied avec de la paille pour conserver la fraîcheur du sol.  5. Cesser l'arrosage 10 jours avant la récolte.",
            'advices' => "1. Si les feuilles jaunissent ou que les fruits cessent de grandir c'est que la plante manque d'eau. 2. C'est une plante frileuse, c'est donc très important que le potimarron soit semé (ou repiqué) après tous risques de gelées. 3. Placer de la paille au pied des plantes pour conserver la fraîcheur du sol. Cela sera également utile pour protéger les feuilles de la terre humide et éviter ainsi qu'elle ne pourrissent. 4. Après la récolte, retirer toute la végétation restante qui peut souvent être porteuse de maladies ou de chamignons.",
            'soil_ph'=> 7,
            'soil_humus_percent'=> 50,
            'soil_granulometry'=> 'limons grossiers',
        ]);

        $choufleur = Seed::create([
            'name' => 'chou-fleur',
            'latin_name' => 'Brassica oleracea var. botrytis',
            'variety' => 'Flora Blanca',
            'type' => 'brassicacée',
            'exposure' => 'ensoleillé / mi-ombre',
            'water' => 'abondant',
            'fertilizer' => 'Ne nécessite aucun engrais',
            'planting_period_start' => '2018-04-01',
            'planting_period_end' => '2018-08-01',
            'harvest_period_start' => '2018-10-01',
            'harvest_period_end' => '2019-02-28',
            'harvest_within_time' => 0,
            'grown_img_url' => '/radis_rond_ecarlate_fruit.jpg',
            'seed_img_url' => '/radis_rond_ecarlate_seed.jpg',
            'price' => '3.00',
            'difficulty' => 'medium',
            'tutorial' => "1. Placer les graines à 1 ou 2cm de profondeur en les espacant de 4cm. 2. Recouvrer de terreau et arrosage. 3. Lorsque le plant a 3-4 feuilles, repiquer les profondément en pleine terre en les espacant de 50 à 70cm. 4. Arroser abondamment.",
            'advices' => "1. Désherber régulièrement afin d'éviter la pousse d'autres plantes car le chou-fleur manque vite d'eau. 2. Été comme hiver, paillez le pied est utile pour la sécheresse mais également pour conserver la chaleur. 3. Éviter d’arroser le feuillage pour les champignons. 4. Lorsqu'il atteint une dizaine de cm de diamètre, protèger le chou-fleur avec les feuilles intérieures du chou.",
            'soil_ph'=> 7,
            'soil_humus_percent'=> 50,
            'soil_granulometry'=> 'limons fins',
        ]);


        /* Illnesses */

        $mildiou = Illness::create([
            'name' => 'mildiou',
            'description' => 'Le mildiou est un champignon qui se propage très facilement dans des conditions humides.',
            'cause' => 'Cette maladie est due à un champignon pathogène, le Phytophtora infestans, se développant principalement par temps humide lorsque la température oscille entre 17 et 20°C. Les alternances d\'épisodes pluvieux et d\'épisodes de chaleur orageuse correspondent aux conditions idéales pour que le mildiou se développe. Par contre, la canicule le stoppe.',
            'consequence' => 'C\'est en atteignant la plante de l’intérieur que le mildiou s’en prend aux végétaux, les faisant alors dépérir. Le mildiou se reconnaît aux petites taches noirâtres et au feutrage blanchâtre qu’il provoque respectivement sur le dessus et le dessous des feuilles. Très vite, les taches vont commencer à brunir, s’étendre aux fruits et à les faire pourrir.',
            'prevention' => 'Sur la vigne, retirer les gourmands pour aérer le feuillage. Dès l\'apparition des premières tâches sur les feuilles de tomates, couper les feuilles atteintes et retirer celles qui traînent au sol. Faites en sorte que vos pieds de tomates soient bien aérés. Les feuilles doivent pouvoir sécher facilement. Dès les premiers signes il est possible de pulvériser de la bouillie bordelaise afin de limiter la dissémination du champignon aux plantes voisines. Poser une toiture au dessus de vos pieds de tomates pour éviter qu\'un excès d\'humidité ne se dépose sur le feuillage.',
            'treatment' => 'Dès l’apparition des premiers symptômes, coupez les parties infectées qui peuvent aller sur le tas de compost, Au tout début de l\'apparition du mildiou, vous pouvez pulvériser une infusion de tanaisie (Tanacetum vulgare) à raison de 100g de fleurs pour 1 litre d\'eau que vous aurez laissé infuser jusqu\'à ce quelle soit froide avant de l\'utiliser pure. Si ce n\'est pas assez puissant, pulvérisez un purin de bardane (feuilles et racines) à raison d\'1kg de plante pour 10 litres d\'eau que vous aurez laissé fermenter 5 à 6 jours avant de le filtrer et de l\'utiliser dilué à 5%. Si la saison est particulièrement pluvieuse, vous pouvez couvrir vos tomates en installant une sorte d\'abri en film plastique.'
        ]);

        $tomatoes->illnesses()->attach($mildiou);

        /* Permaculture */

        $tomatoes->permacultures()->attach($leek, ['positive_effect' => true, 'location' => 'after']);


    }
}
